name: andlig_app
description: Andlig Väg – Flutter-app
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Arkitektur
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0

  # Backend/infra
  supabase_flutter: ^2.6.0
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.2.2

  # UI
  google_fonts: ^6.2.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - .env
